import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export interface InvoiceItem {
  id?: string;
  product_id: string;
  product_name: string;
  quantity: number;
  unit_price: number;
  total_price: number;
}

export interface CreateInvoiceData {
  client_id: string;
  po_number?: string;
  due_date?: string;
  notes?: string;
  tax_rate: number;
  tax_included: boolean;
  items: InvoiceItem[];
  // New fields for localization & currency
  currency?: 'CNY' | 'USD';
  fx_to_cny?: number;
  language?: 'zh' | 'en';
}

export interface Invoice {
  id: string;
  invoice_number: string;
  po_number?: string;
  client_id: string;
  subtotal: number; // Stored in CNY for accounting
  tax_amount: number; // Stored in CNY for accounting
  tax_rate: number;
  tax_included: boolean;
  total_amount: number; // Stored in CNY for accounting
  payment_status: 'pending' | 'paid' | 'overdue' | 'cancelled';
  due_date?: string;
  paid_date?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  // New fields
  currency: 'CNY' | 'USD';
  fx_to_cny: number;
  subtotal_original?: number | null;
  tax_amount_original?: number | null;
  total_amount_original?: number | null;
  language: 'zh' | 'en';
  client?: {
    id: string;
    name: string;
    company_name?: string;
    contact_person?: string;
    email: string;
    phone?: string;
    address?: string;
  };
  invoice_items?: Array<{
    id: string;
    product_id: string;
    quantity: number;
    unit_price: number;
    total_price: number;
    product: {
      id: string;
      name: string;
      sku: string;
      category: string;
    };
  }>;
}

export const useInvoices = () => {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchInvoices = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from("mo-invoices")
        .select(`
          *,
          client:"mo-clients"(*),
          invoice_items:"mo-invoice_items"(
            *,
            product:"mo-products"(id, name, sku, category)
          )
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      
      setInvoices((data || []).map((d: any) => ({
        ...d,
        currency: d.currency === 'USD' ? 'USD' : 'CNY',
        language: d.language === 'en' ? 'en' : 'zh',
      })) as Invoice[]);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to fetch invoices",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const createInvoice = async (invoiceData: CreateInvoiceData) => {
    try {
      setLoading(true);

      // Defaults to maintain backward compatibility
      const currency = invoiceData.currency ?? 'CNY';
      const fx_to_cny = invoiceData.fx_to_cny ?? 1;
      const language = invoiceData.language ?? 'zh';

      // Calculate totals in ORIGINAL currency (based on current item prices)
      const itemsSubtotal = invoiceData.items.reduce((sum, item) => sum + item.total_price, 0);
      let subtotal_original = itemsSubtotal;
      let tax_amount_original = 0;
      let total_amount_original = itemsSubtotal;

      if (invoiceData.tax_included) {
        tax_amount_original = itemsSubtotal * (invoiceData.tax_rate / 100) / (1 + invoiceData.tax_rate / 100);
        subtotal_original = itemsSubtotal - tax_amount_original;
        total_amount_original = itemsSubtotal;
      } else {
        tax_amount_original = itemsSubtotal * (invoiceData.tax_rate / 100);
        total_amount_original = itemsSubtotal + tax_amount_original;
      }

      // Convert to CNY for accounting
      const rate = currency === 'USD' ? (fx_to_cny || 1) : 1;
      const subtotal_cny = subtotal_original * rate;
      const tax_amount_cny = tax_amount_original * rate;
      const total_amount_cny = total_amount_original * rate;

      // Create invoice (invoice_number will be auto-generated by database trigger)
      const { data: invoice, error: invoiceError } = await supabase
        .from("mo-invoices")
        .insert({
          client_id: invoiceData.client_id,
          po_number: invoiceData.po_number || null,
          // Accounting totals in CNY
          subtotal: subtotal_cny,
          tax_amount: tax_amount_cny,
          tax_rate: invoiceData.tax_rate,
          tax_included: invoiceData.tax_included,
          total_amount: total_amount_cny,
          due_date: invoiceData.due_date || null,
          notes: invoiceData.notes || null,
          payment_status: 'pending' as const,
          invoice_number: `INV-${Date.now()}`, // fallback
          // New fields
          currency,
          fx_to_cny,
          language,
          subtotal_original,
          tax_amount_original,
          total_amount_original,
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice items
      const items = invoiceData.items.map(item => ({
        invoice_id: invoice.id,
        product_id: item.product_id,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
      }));

      const { error: itemsError } = await supabase
        .from("mo-invoice_items")
        .insert(items);

      if (itemsError) throw itemsError;

      toast({
        title: "Success",
        description: "Invoice created successfully",
      });

      await fetchInvoices();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to create invoice",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const updateInvoiceStatus = async (invoiceId: string, status: string) => {
    try {
      const updateData: any = { payment_status: status };
      if (status === 'paid') {
        updateData.paid_date = new Date().toISOString().split('T')[0];
      }

      const { error } = await supabase
        .from("mo-invoices")
        .update(updateData)
        .eq("id", invoiceId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Invoice status updated",
      });

      await fetchInvoices();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update invoice status",
        variant: "destructive",
      });
    }
  };

  const deleteInvoice = async (invoiceId: string) => {
    try {
      // Delete invoice items first
      const { error: itemsError } = await supabase
        .from("mo-invoice_items")
        .delete()
        .eq("invoice_id", invoiceId);

      if (itemsError) throw itemsError;

      // Delete invoice
      const { error } = await supabase
        .from("mo-invoices")
        .delete()
        .eq("id", invoiceId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Invoice deleted successfully",
      });

      await fetchInvoices();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to delete invoice",
        variant: "destructive",
      });
    }
  };

  useEffect(() => {
    fetchInvoices();
  }, []);

  const updateInvoice = async (invoiceId: string, invoiceData: Partial<CreateInvoiceData>) => {
    try {
      setLoading(true);

      if (invoiceData.items) {
        // Defaults to maintain compatibility if fields are missing
        const currency = invoiceData.currency ?? 'CNY';
        const fx_to_cny = invoiceData.fx_to_cny ?? 1;
        const language = invoiceData.language ?? 'zh';
        const tax_rate = invoiceData.tax_rate ?? 10;
        const tax_included = invoiceData.tax_included ?? false;

        // Calculate totals in ORIGINAL currency
        const itemsSubtotal = invoiceData.items.reduce((sum, item) => sum + item.total_price, 0);
        let subtotal_original = itemsSubtotal;
        let tax_amount_original = 0;
        let total_amount_original = itemsSubtotal;

        if (tax_included) {
          tax_amount_original = itemsSubtotal * (tax_rate / 100) / (1 + tax_rate / 100);
          subtotal_original = itemsSubtotal - tax_amount_original;
          total_amount_original = itemsSubtotal;
        } else {
          tax_amount_original = itemsSubtotal * (tax_rate / 100);
          total_amount_original = itemsSubtotal + tax_amount_original;
        }

        // Convert to CNY for accounting
        const rate = currency === 'USD' ? (fx_to_cny || 1) : 1;
        const subtotal_cny = subtotal_original * rate;
        const tax_amount_cny = tax_amount_original * rate;
        const total_amount_cny = total_amount_original * rate;

        // Update invoice
        const { error: invoiceError } = await supabase
          .from("mo-invoices")
          .update({
            client_id: invoiceData.client_id,
            po_number: invoiceData.po_number || null,
            // Accounting totals in CNY
            subtotal: subtotal_cny,
            tax_amount: tax_amount_cny,
            tax_rate,
            tax_included,
            total_amount: total_amount_cny,
            due_date: invoiceData.due_date || null,
            notes: invoiceData.notes || null,
            // New fields
            currency,
            fx_to_cny,
            language,
            subtotal_original,
            tax_amount_original,
            total_amount_original,
          })
          .eq("id", invoiceId);

        if (invoiceError) throw invoiceError;

        // Replace invoice items
        const { error: deleteError } = await supabase
          .from("mo-invoice_items")
          .delete()
          .eq("invoice_id", invoiceId);
        if (deleteError) throw deleteError;

        const items = invoiceData.items.map(item => ({
          invoice_id: invoiceId,
          product_id: item.product_id,
          quantity: item.quantity,
          unit_price: item.unit_price,
          total_price: item.total_price,
        }));

        const { error: itemsError } = await supabase
          .from("mo-invoice_items")
          .insert(items);
        if (itemsError) throw itemsError;
      } else {
        // Update only invoice fields (without items)
        const currency = invoiceData.currency ?? undefined;
        const fx_to_cny = invoiceData.fx_to_cny ?? undefined;
        const language = invoiceData.language ?? undefined;

        const { error } = await supabase
          .from("mo-invoices")
          .update({
            client_id: invoiceData.client_id,
            po_number: invoiceData.po_number || null,
            due_date: invoiceData.due_date || null,
            notes: invoiceData.notes || null,
            tax_rate: invoiceData.tax_rate ?? undefined,
            tax_included: invoiceData.tax_included ?? undefined,
            currency,
            fx_to_cny,
            language,
          })
          .eq("id", invoiceId);

        if (error) throw error;
      }

      toast({
        title: "Success",
        description: "Invoice updated successfully",
      });

      await fetchInvoices();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update invoice",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return {
    invoices,
    loading,
    createInvoice,
    updateInvoice,
    updateInvoiceStatus,
    deleteInvoice,
    refetch: fetchInvoices,
  };
};
